version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/openrouter-toolkit-chat-completion/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/ui/extensions/openrouter-toolkit-ui/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
