version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/openrouter-toolkit-chat-completion/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: npm
    directory: "/ui/extensions/openrouter-toolkit-ui/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
          - "@types/jest"
          - "ts-jest"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
