name: OpenRouter Toolkit Query
description: 'Submit chat completion requests to OpenRouter Toolkit. '
provision_on_install: true
trigger:
    next:
        - openrouter_toolkit_chat_completion_6946b508
    name: On demand
    parameters:
        properties:
            temperature_input:
                type: string
                default: "0.4"
            model_name_input:
                type: string
                default: openrouter/auto
            user_prompt_input:
                type: string
            online_input:
                type: boolean
                default: false
            context_data_input:
                type: string
                description: "JSON string containing context data from falcon.data for enhanced analysis"
            provider_sort_input:
                type: string
                description: "Provider sorting preference: price, throughput, or latency"
        required:
            - user_prompt_input
        type: object
actions:
    openrouter_toolkit_chat_completion_6946b508:
        id: functions.openrouter-toolkit-chat-completion.OpenRouter Toolkit Chat Completion
        properties:
            model_name_input: ${model_name_input}
            temperature_input: ${temperature_input}
            online_input: ${online_input}
            context_data_input: ${context_data_input}
            provider_sort_input: ${provider_sort_input}
            user_prompt_input: ${user_prompt_input}
output_fields:
    - openrouter_toolkit_chat_completion_6946b508.FaaS.openrouter-toolkit-chat-completion.OpenRouterToolkitChatCompletion.model_output_text
    - openrouter_toolkit_chat_completion_6946b508.FaaS.openrouter-toolkit-chat-completion.OpenRouterToolkitChatCompletion.execution_time_ms
summary: |-
    ${openrouter_toolkit_chat_completion_6946b508.FaaS.openrouter-toolkit-chat-completion.OpenRouterToolkitChatCompletion.execution_time_ms}

    ${openrouter_toolkit_chat_completion_6946b508.FaaS.openrouter-toolkit-chat-completion.OpenRouterToolkitChatCompletion.model_output_text}
